###

GET http://localhost:8080/flats

###

GET http://localhost:8080/flats/1

###

POST http://localhost:8080/flats
Content-Type: application/json

{
"url": "http://....",
"image": "http://...",
"residentialComplex": "ЖК 'Казань 21 век'",
"address": "пр-т Альберта Камалеева, д.32Б",
"district": "Советский",
"numberOfRooms": "1",
"area": "33",
"floor": "17",
"totalFloor": "19",
"metroStation": "Метро Горки",
"price": "4350000",
"realEstateAgency": "Агенство недвижимости Ключ"
}

###

POST http://localhost:8080/flats
Content-Type: application/json

{
"url": "http://....",
"image": "http://...",
"residentialComplex": "ЖК Жилой дом",
"address": "ул.К.Маркса,д.39А",
"district": "Вахитовский",
"numberOfRooms": "3",
"area": "132",
"floor": "4",
"totalFloor": "5",
"metroStation": "Метро Площадь Тукая",
"price": "21500000",
"realEstateAgency": "Агенство недвижимости Ключ"
}

###

PUT http://localhost:8080/flats/1
Content-Type: application/json

{
"image": "http://...",
"price": "4000000"
}

###

DELETE http://localhost:8080/flats/1



