###

GET https://flats-avito.herokuapp.com/flats

###

GET https://flats-avito.herokuapp.com/flats/1

###

GET https://flats-avito.herokuapp.com/flats/search?minPrice=4060000&maxPrice=21500000


###

POST https://flats-avito.herokuapp.com/flats
Content-Type: application/json

{
"url": "http://....",
"image": "http://...",
"residentialComplex": "ЖК 'Казань 21 век'",
"address": "пр-т Альберта Камалеева, д.32Б",
"district": "Советский",
"numberOfRooms": "1",
"area": "33",
"floor": "17",
"totalFloor": "19",
"metroStation": "Метро Горки",
"price": "4350000",
"realEstateAgency": "Агенство недвижимости Ключ"
}

###

POST https://flats-avito.herokuapp.com/flats
Content-Type: application/json

{
"url": "http://....",
"image": "http://...",
"residentialComplex": "ЖК Жилой дом",
"address": "ул.К.Маркса,д.39А",
"district": "Вахитовский",
"numberOfRooms": "3",
"area": "132",
"floor": "4",
"totalFloor": "5",
"metroStation": "Метро Площадь Тукая",
"price": "21500000",
"realEstateAgency": "Агенство недвижимости Ключ"
}

###

POST https://flats-avito.herokuapp.com/flats
Content-Type: application/json

{
  "url": "http://....",
  "image": "http://...",
  "residentialComplex": "ЖК Станция Спортивная",
  "address": "пр-д Детский, д. 1,к2",
  "district": "Приволжский",
  "numberOfRooms": "1",
  "area": "31.2",
  "floor": "9",
  "totalFloor": "19",
  "price": "4060000"
}

###

PUT https://flats-avito.herokuapp.com/flats/1
Content-Type: application/json

{
"image": "http://...",
"price": "4000000"
}

###

DELETE https://flats-avito.herokuapp.com/flats/1
Content-Type: application/json





